### ISSUE TITLE
Only france-reg, france-reg-2016, france-dep, usa-states are available?

### ISSUE THREAD

**Issue by duleise** [dreamRs/topogRam#2]
Any chance more regions will be included?
Thank you.

**Comment by pvictor** [comment]
Yes more regions can be included ! Which one do you want ?
I can add the shape to the package like the other and I will also look if it's possible to pass geo shape as an argument.

**Comment by duleise** [comment]
Thank you.
How about Sweden?

**Comment by pvictor** [comment]
I've integrated the first level of administrative divisions for Sweden, you can test with : 

```r
devtools::install_github("pvictor/topogRam")
library(topogRam)

# Population data
sweden_data <- data.frame(
  id = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"),
  name = c("Östergötland", "Blekinge", "Dalarna", "Gävleborg", "Gotland", "Halland", "Jämtland", "Jönköping", "Kalmar", 
           "Kronoberg", "Norrbotten", "Orebro", "Södermanland", "Skåne", "Stockholm", "Uppsala", "Värmland", "Västerbotten", "Västernorrland", 
           "Västmanland", "Västra Götaland"),
  population = c(452105, 158453, 284531, 284586, 284586, 320333, 128673, 352735, 242301, 194628, 250570, 294941, 288097, 1324565, 2269060,
                 361373, 279334, 265881, 245572, 267629, 1671783),
  stringsAsFactors = FALSE
)

# Make a topogRam
topogRam(
  data = sweden_data,
  shape = "sweden-1",
  key_var = "population",
  geo_lab = "name",
  colors = brewer.pal("Reds", n = 3),
  origin = c(22, 60), scale = 2500
)


# Create a random variable
sweden_data$random <- sample(sweden_data$population)

# Test with two variables
topogRam(
  data = sweden_data,
  shape = "sweden-1",
  key_var = c("population", "random"),
  geo_lab = "name",
  colors = brewer.pal("Reds", n = 3),
  origin = c(22, 60), scale = 2500
)
```

**Comment by duleise** [comment]
Thank you so much. It works smoothly.
I guess the core part is the shape file you created for Sweden. I am wondering if it's possible to create it by myself? I may need deeper level, or certain regions for example.
Thank you again for you prompt response.

**Comment by pvictor** [comment]
You're welcome! You're right the core part is the shape file, it's in fact a topojson; The step to create it are a little manual for the moment, i'll look to automatize and describe the process.

**Comment by popovs** [comment]
Would be great if in the future we can just point to some Spatial Data Frame/shapefile and have toporgRam do the rest!

**Comment by pvictor** [comment]
Yes it would be top, what's complicated is that topogram.js needs topojson to work, I'll try to find some time to see if a standalone R solution exists. And I'll migrate to D3v4 too.

**Comment by pvictor** [comment]
This works now for any `sf` objects, try this (or with any country) for example : 

```r
library(rnaturalearth)
library(topogRam)

sweden <- ne_states(country = "sweden", returnclass = "sf")
sweden$foo <- floor(runif(nrow(sweden), 500, 5000))

topogRam(sweden, "foo")
```

![image](https://user-images.githubusercontent.com/4415580/46499846-8a072480-c821-11e8-8eba-7c26faf4baad.png)


Victor
